# Generated by Django 3.0.6 on 2020-11-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_titre', models.CharField(max_length=500)),
                ('fichier_description', models.CharField(max_length=1000)),
                ('fichier_file', models.FileField(upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_infos', models.CharField(max_length=1000)),
                ('user_logo', models.FileField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('trello_id', models.CharField(db_index=True, max_length=500)),
                ('has_random_password', models.BooleanField(default=True)),
            ],
        ),
    ]
