# Generated by Django 3.0.6 on 2020-11-29 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trelloBoard', '0001_initial'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='organizations',
            field=models.ManyToManyField(to='trelloBoard.Organization'),
        ),
        migrations.AddField(
            model_name='personne',
            name='usager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doc',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Personne'),
        ),
    ]
